springfox:
  documentation:
    swagger-ui:
      enabled: false
  # 다음의 'documentation' 키는 불필요하므로 삭제하세요
  # documentation:
  #   enabled: false

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    #username: cos
    #password: cos1234
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true




